### ISSUE TITLE
Raster publisher: Missing zip, cannot create reader

### ISSUE THREAD

**Issue by jdk24** [meggsimum/sauber-sdi-docker#82]
### Steps to reproduce
Pulled #81, built raster_publisher image, deployed raster_publisher in stack. 

### Environment
1. Empty GeoServer mount
2.  GS Image mosaics not initiated
3. Inserted two rasters into database, published raster metadata

### Expected behaviour
1. Find unpublished rasters through PostgREST raster metadata. 
2. Create coverage store "nrw_pm10_gm1h24h". 
3. Add and publish two new raster granules. 

### Actual behaviour

1. On initial run, raster publisher cannot find ` zip`. 
Logfile attached as [1_log_raster_publisher.txt](https://github.com/meggsimum/sauber-sdi-docker/files/6611379/1_log_raster_publisher.txt)

2. After `apk update && apk add zip `, generic GeoServer error: Failed to create reader.
Raster publisher cannot create coverage store and add granules. 
Logfile attached: [2_log_raster_publisher.txt](https://github.com/meggsimum/sauber-sdi-docker/files/6611378/2_log_raster_publisher.txt)

**Comment by jdk24** [comment]
Possibly related: GeoServer Init throws errors [like so](https://github.com/meggsimum/sauber-sdi-docker/files/6626841/log_geoserver_init.txt).

Docker Secrets are available in both init and publisher.

**Comment by chrismayer** [comment]
Point 1.) is done in #85.

**Comment by chrismayer** [comment]
> Possibly related: GeoServer Init throws errors

The _GeoServer Init_ could not connect to the GeoServer REST-API (`"Could not connect to GeoServer REST API - ABORT!"`). Either the GeoServer was not there at all at this time (quite unlikely) or the credentials were wrong. What is done in the  _GeoServer Init_ is logging in with the GS default credentials and change them in the first step of the script to the credentials in the secrets.

**Comment by chrismayer** [comment]
I had a look on this. Besides the point that the DB password in the datastore.properties was hard coded and is now set by secret (see #61 ) there are renaming issues which lead to the described `Could not acquire reader for coverage.` error when creating the CoverageStore. The error seems to be data related or caused by a mismatch of the tif file(s) and the ImageMosaic configurations in the` datastore|indexer|timeregex.properties` files. When using an arbitrary test geotiff from our server `Could not acquire reader for coverage.` occurs. Only when using the geotiffs in `/opt/raster_data/nrw/pm10_gm1h24h/` the CoverageStore creation succeeds.

**Comment by chrismayer** [comment]
Can this be closed @jdk24 ?

**Comment by jdk24** [comment]
> 
> 
> Can this be closed @jdk24 ?

Closed as all issues were solved. Thanks awfully!
